"""empty message

Revision ID: 065f090aa4a3
Revises: 4d6ef7aeb2d8
Create Date: 2020-02-04 13:52:49.882063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '065f090aa4a3'
down_revision = '4d6ef7aeb2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeled_clips', sa.Column('offset', sa.Float(), nullable=True))
    op.drop_column('labeled_clips', 'start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeled_clips', sa.Column('start', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('labeled_clips', 'offset')
    # ### end Alembic commands ###
