"""empty message

Revision ID: 0abb957cdf18
Revises: 997839a36d2d
Create Date: 2020-04-10 03:40:11.757891

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0abb957cdf18'
down_revision = '997839a36d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('monitoring_stations', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'monitoring_stations', 'projects', ['project_id'], ['id'])
    op.drop_column('users', 'tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tokens', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'monitoring_stations', type_='foreignkey')
    op.drop_column('monitoring_stations', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
