"""empty message

Revision ID: 1f4398023590
Revises: 801df81161bd
Create Date: 2020-04-21 13:04:03.767788

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1f4398023590'
down_revision = '801df81161bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeled_clips', sa.Column('sub_label_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'labeled_clips', 'labels', ['sub_label_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labeled_clips', type_='foreignkey')
    op.drop_column('labeled_clips', 'sub_label_id')
    # ### end Alembic commands ###
