"""empty message

Revision ID: 2a7423a8226a
Revises: bfaa60c81835
Create Date: 2021-07-06 02:22:04.760506

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2a7423a8226a'
down_revision = 'bfaa60c81835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iteration_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('offset', sa.Float(), nullable=False),
    sa.Column('should_be_id', sa.Integer(), nullable=False),
    sa.Column('came_out_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['came_out_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['file_name'], ['audio_files.name'], ),
    sa.ForeignKeyConstraint(['iteration_id'], ['model_iterations.id'], ),
    sa.ForeignKeyConstraint(['should_be_id'], ['labels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('model_iterations', sa.Column('accuracy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_iterations', 'accuracy')
    op.drop_table('training_errors')
    # ### end Alembic commands ###
