"""empty message

Revision ID: 315d32134548
Revises: 9b1c77cdb9d8
Create Date: 2020-11-10 05:55:53.438668

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '315d32134548'
down_revision = '9b1c77cdb9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_labeled_clips_file_name'), 'labeled_clips', ['file_name'], unique=False)
    op.create_index(op.f('ix_labeled_clips_label_id'), 'labeled_clips', ['label_id'], unique=False)
    op.create_index(op.f('ix_labeled_clips_offset'), 'labeled_clips', ['offset'], unique=False)
    op.create_index(op.f('ix_model_outputs_file_name'), 'model_outputs', ['file_name'], unique=False)
    op.create_index(op.f('ix_model_outputs_label_id'), 'model_outputs', ['label_id'], unique=False)
    op.create_index(op.f('ix_model_outputs_offset'), 'model_outputs', ['offset'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_outputs_offset'), table_name='model_outputs')
    op.drop_index(op.f('ix_model_outputs_label_id'), table_name='model_outputs')
    op.drop_index(op.f('ix_model_outputs_file_name'), table_name='model_outputs')
    op.drop_index(op.f('ix_labeled_clips_offset'), table_name='labeled_clips')
    op.drop_index(op.f('ix_labeled_clips_label_id'), table_name='labeled_clips')
    op.drop_index(op.f('ix_labeled_clips_file_name'), table_name='labeled_clips')
    # ### end Alembic commands ###
