"""empty message

Revision ID: 47f204dc0ab6
Revises: c25b9db867bd
Create Date: 2022-02-16 23:22:10.641186

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '47f204dc0ab6'
down_revision = 'c25b9db867bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iteration_id', sa.Integer(), nullable=False),
    sa.Column('labeled_clip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['model_iterations.id'], ),
    sa.ForeignKeyConstraint(['labeled_clip_id'], ['labeled_clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_clips')
    # ### end Alembic commands ###
