"""empty message

Revision ID: 5407f77a0084
Revises: d343513eee56
Create Date: 2020-02-03 22:44:21.646463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5407f77a0084'
down_revision = 'd343513eee56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['label_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('labeled_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('start', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_name'], ['audio_files.name'], ),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('clusters', 'cg_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('common_name', sa.Column('label_id', sa.Integer(), nullable=True))
    op.drop_constraint('common_name_species_id_fkey', 'common_name', type_='foreignkey')
    op.create_foreign_key(None, 'common_name', 'labels', ['label_id'], ['id'])
    op.drop_column('common_name', 'species_id')
    op.drop_table('identifications')
    op.drop_table('species')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_name', sa.Column('species_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'common_name', type_='foreignkey')
    op.create_foreign_key('common_name_species_id_fkey', 'common_name', 'species', ['species_id'], ['id'])
    op.drop_column('common_name', 'label_id')
    op.alter_column('clusters', 'cg_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('species',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('species_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='species_pkey'),
    sa.UniqueConstraint('name', name='species_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('identifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('duration', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('species_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['audio_files.id'], name='identifications_file_id_fkey'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name='identifications_species_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='identifications_pkey')
    )
    op.drop_table('labeled_clips')
    op.drop_table('labels')
    op.drop_table('label_types')
    # ### end Alembic commands ###
