"""empty message

Revision ID: 557f34273964
Revises: 47f204dc0ab6
Create Date: 2022-03-01 13:47:50.346236

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '557f34273964'
down_revision = '47f204dc0ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_files', 'sn',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'audio_files', 'equipment', ['sn'], ['serial_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio_files', type_='foreignkey')
    op.alter_column('audio_files', 'sn',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
