"""empty message

Revision ID: 56c4fdc303a3
Revises: 1f4398023590
Create Date: 2020-04-22 14:32:07.921498

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '56c4fdc303a3'
down_revision = '1f4398023590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeled_clips', sa.Column('certain', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labeled_clips', 'certain')
    # ### end Alembic commands ###
