"""empty message

Revision ID: 61e62c4d3bea
Revises: 9514f46e4cef
Create Date: 2020-12-20 03:12:55.168044

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '61e62c4d3bea'
down_revision = '9514f46e4cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeled_clips', sa.Column('exact_time', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labeled_clips', 'exact_time')
    # ### end Alembic commands ###
