"""empty message

Revision ID: 6c3661390924
Revises: 815d03f61fc4
Create Date: 2020-01-15 15:16:45.605122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3661390924'
down_revision = '815d03f61fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_name', sa.Column('notes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_name', 'notes')
    # ### end Alembic commands ###
