"""empty message

Revision ID: 801df81161bd
Revises: fd903dd7e939
Create Date: 2020-04-20 18:56:16.647050

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '801df81161bd'
down_revision = 'fd903dd7e939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_types', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'label_types', 'label_types', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'label_types', type_='foreignkey')
    op.drop_column('label_types', 'parent_id')
    # ### end Alembic commands ###
