"""empty message

Revision ID: 815d03f61fc4
Revises: dc5b27517c67
Create Date: 2020-01-13 19:14:32.508824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815d03f61fc4'
down_revision = 'dc5b27517c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('clusters', sa.Column('cg_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clusters', 'cluster_groups', ['cg_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clusters', type_='foreignkey')
    op.drop_column('clusters', 'cg_id')
    op.drop_table('cluster_groups')
    # ### end Alembic commands ###
