"""empty message

Revision ID: 97cdf7d1477e
Revises: 9dacd312aef4
Create Date: 2021-06-10 17:29:47.562088

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '97cdf7d1477e'
down_revision = '9dacd312aef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_models', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_models', 'description')
    # ### end Alembic commands ###
