"""empty message

Revision ID: 9b1c77cdb9d8
Revises: 56c4fdc303a3
Create Date: 2020-09-15 02:47:19.778935

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9b1c77cdb9d8'
down_revision = '56c4fdc303a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iteration_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('combine_with_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['combine_with_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['iteration_id'], ['model_iterations.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_labels')
    # ### end Alembic commands ###
