"""empty message

Revision ID: 9c50ab229018
Revises: 065f090aa4a3
Create Date: 2020-02-07 19:18:38.114641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c50ab229018'
down_revision = '065f090aa4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IN FILE', sa.String(length=255), nullable=True),
    sa.Column('OFFSET', sa.Float(), nullable=True),
    sa.Column('DURATION', sa.Float(), nullable=True),
    sa.Column('TOP1MATCH', sa.String(length=255), nullable=True),
    sa.Column('MANUAL ID', sa.String(length=255), nullable=True),
    sa.Column('cg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IN FILE'], ['audio_files.name'], ),
    sa.ForeignKeyConstraint(['cg_id'], ['cluster_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clusters')
    op.drop_table('cluster_groups')
    # ### end Alembic commands ###
