"""empty message

Revision ID: 9dacd312aef4
Revises: 18bcda1a1374
Create Date: 2021-06-06 10:57:38.873821

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9dacd312aef4'
down_revision = '18bcda1a1374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum_postgres = postgresql.ENUM('labeling', 'ready_to_train', 'training', 'trained', 'ready_to_run', 'running', 'finished', name='status_enum', create_type=False)
    status_enum_postgres.create(op.get_bind(), checkfirst=False)
    status_enum = sa.Enum('labeling', 'ready_to_train', 'training', 'trained', 'ready_to_run', 'running', 'finished', name='status_enum')
    status_enum.with_variant(status_enum_postgres, 'postgresql')
    op.add_column('model_iterations', sa.Column('status', status_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_iterations', 'status')
    # ### end Alembic commands ###
