"""empty message

Revision ID: 9f27eae10c36
Revises: 30ab74661e9a
Create Date: 2020-04-13 00:55:54.791300

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9f27eae10c36'
down_revision = '30ab74661e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('model_iterations', sa.Column('model_id', sa.Integer(), nullable=False))
    op.drop_constraint('model_iterations_project_id_fkey', 'model_iterations', type_='foreignkey')
    op.create_foreign_key(None, 'model_iterations', 'ml_models', ['model_id'], ['id'])
    op.drop_column('model_iterations', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_iterations', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model_iterations', type_='foreignkey')
    op.create_foreign_key('model_iterations_project_id_fkey', 'model_iterations', 'projects', ['project_id'], ['id'])
    op.drop_column('model_iterations', 'model_id')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
