"""empty message

Revision ID: c25b9db867bd
Revises: 379c54c16629
Create Date: 2022-01-21 16:55:44.841551

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c25b9db867bd'
down_revision = '379c54c16629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('code3', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language', 'code3')
    # ### end Alembic commands ###
